# Site settings
title: Sydney Pollock
email: your.email@example.com
description: >-
  Portfolio and professional website
baseurl: ""
url: "https://sydney-pollock.github.io"

# Build settings
markdown: kramdown
theme: minima

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Default values
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
